### ISSUE TITLE
Server failing to parse FLAP header

### ISSUE THREAD

**Issue by sunnydayoutside** [mk6i/retro-aim-server#7] opened 2024-04-09 02:34 UTC
While chatting with a friend ("doodledunce" in this scenario) on AIM Pro 1.5.0, I sent a message to my friend, and the server immediately disconnected the client.

The server returns with this error:
![image](https://github.com/mk6i/retro-aim-server/assets/59892936/e61c5264-c31d-44b5-a7dd-8457dbbe39ef)

I thought it was the client sending some sort of malformed data at first, but it actually wasn't.

Here is the packet that was sent by the client (the recipient was "doodledunce" and the message was ";").

`2a0250a000660004000600006b470006c00e6bd114da5ff500010b646f6f646c6564756e636500020022050100010101010019000000003c464f4e542073697a653d323e273c2f464f4e543e000d001c0082000c2c61696d70726f7369646531000100082c61705f69636f6e`

AFAIK, this sort of behavior isn't demonstrated on clients like AIM 5.9. I know that other clients, like AIM Lite, will also send packets and will also get disconnected.

I hope this bug gets solved soon, when clients like these get disconnected they usually crash. (P.S You can use [FLAP__FRAME_SIGNOFF](https://wiki.nina.chat/wiki/Protocols/OSCAR/FLAP#FLAP_FRAME_SIGNOFF) to gracefully inform clients that they're being disconnected.)

Thanks,
LushPineapple29

**Comment by mk6i** [comment] 2024-04-09 02:45
Thanks for the report! 

Unfortunately, RAS does not currently target AIM Pro. Right now only Windows AIM 5.0-5.9 from the years 2002-2006 are supported. It looks like that version of AIM Pro is from 2011.

I'll check to see if there's any quick fix for this version (admittedly, I've never used AIM Pro). If not, I'll add this ticket to the backlog. I'm currently working on supporting AIM 4.8 and am working backwards towards 3.0.

**Comment by mk6i** [comment] 2024-04-09 02:47
To clarify, do all the messages fail, or just the one that had the semicolon?

**Comment by mk6i** [comment] 2024-04-10 03:45
So I just tried to AIM Pro and was not able to reproduce the issue. I do have an idea of what might be happening, though.

- Does the issue happen consistently or randomly?
- Do you have the full server log to share?

**Comment by mk6i** [comment] 2024-04-13 14:43
Fixed in [v0.2.0](https://github.com/mk6i/retro-aim-server/releases/tag/v0.2.0). Please re-open this issue if you see the problem happen again.

**Closed by mk6i** 2024-04-13 14:43 UTC
Labels: bug
